name: pre-merge

on: [push, pull_request]

jobs:
    lint:
        name: Analyze
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Check code style
              run: npm exec -- prettier -c **/*.ts
            - name: Lint with eslint
              run: npm run eslint
